language: node_js
node_js: node

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run pretty

before_deploy:
  - npm i -g netlify-cli
  - npm run build

deploy:
  provider: script
  script: netlify deploy --prod --message "$TRAVIS_COMMIT - $TRAVIS_COMMIT_MESSAGE"
  skip_cleanup: true
  on:
    branch: master
